//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_clothe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bienthesanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bienthesanpham()
        {
            this.Chitietdonhangs = new HashSet<Chitietdonhang>();
            this.Chitietphieunhaps = new HashSet<Chitietphieunhap>();
        }
    
        public int ID_Bienthesanpham { get; set; }
        public Nullable<int> ID_Sanpham { get; set; }
        public Nullable<int> ID_Mau { get; set; }
        public int Soluongton { get; set; }
        public Nullable<int> SizeID { get; set; }
    
        public virtual MauSac MauSac { get; set; }
        public virtual Sanpham Sanpham { get; set; }
        public virtual Size Size { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietphieunhap> Chitietphieunhaps { get; set; }
    }
}
