//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_clothe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietdonhang
    {
        public int ID_Chitietdonhang { get; set; }
        public Nullable<int> ID_Donhang { get; set; }
        public Nullable<int> ID_Sanphambienthe { get; set; }
        public int Soluong { get; set; }
        public double Thanhtien { get; set; }
    
        public virtual Bienthesanpham Bienthesanpham { get; set; }
        public virtual Donmuahang Donmuahang { get; set; }
    }
}
