//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_clothe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietphieunhap
    {
        public int ID_Chitietphieunhap { get; set; }
        public Nullable<int> ID_Bienthesanpham { get; set; }
        public int Soluongnhap { get; set; }
        public double Thanhtiennhap { get; set; }
        public Nullable<int> ID_Phieunhaphang { get; set; }
    
        public virtual Bienthesanpham Bienthesanpham { get; set; }
        public virtual Phieunhap Phieunhap { get; set; }
    }
}
