//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_clothe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chitietdanhmuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chitietdanhmuc()
        {
            this.Sanphams = new HashSet<Sanpham>();
        }
    
        public int ID_Chitietdanhmuc { get; set; }
        public Nullable<int> Madanhmuc { get; set; }
        public string Tenchitietdanhmuc { get; set; }
        public string HinhAnh { get; set; }
    
        public virtual Danhmucsanpham Danhmucsanpham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanpham> Sanphams { get; set; }
    }
}
