//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_clothe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Server_clothesEntities5 : DbContext
    {
        public Server_clothesEntities5()
            : base("name=Server_clothesEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bienthesanpham> Bienthesanphams { get; set; }
        public virtual DbSet<Chitietdanhmuc> Chitietdanhmucs { get; set; }
        public virtual DbSet<Chitietdonhang> Chitietdonhangs { get; set; }
        public virtual DbSet<Chitietphieunhap> Chitietphieunhaps { get; set; }
        public virtual DbSet<Danhmucsanpham> Danhmucsanphams { get; set; }
        public virtual DbSet<Donmuahang> Donmuahangs { get; set; }
        public virtual DbSet<HinhanhSanpham> HinhanhSanphams { get; set; }
        public virtual DbSet<Loai> Loais { get; set; }
        public virtual DbSet<MauSac> MauSacs { get; set; }
        public virtual DbSet<Nguoidung> Nguoidungs { get; set; }
        public virtual DbSet<Nhacungcap> Nhacungcaps { get; set; }
        public virtual DbSet<Phieunhap> Phieunhaps { get; set; }
        public virtual DbSet<Sanpham> Sanphams { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Thuonghieu> Thuonghieux { get; set; }
        public virtual DbSet<TrangThaiDH> TrangThaiDHs { get; set; }
    }
}
