//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_clothe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donmuahang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donmuahang()
        {
            this.Chitietdonhangs = new HashSet<Chitietdonhang>();
        }
    
        public int ID_Donhang { get; set; }
        public Nullable<int> ID_Nguoidung { get; set; }
        public string DiaChi { get; set; }
        public string Tennguoidung { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public Nullable<double> Tongdonhang { get; set; }
        public Nullable<int> ID_Trangthai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietdonhang> Chitietdonhangs { get; set; }
        public virtual Nguoidung Nguoidung { get; set; }
        public virtual TrangThaiDH TrangThaiDH { get; set; }
    }
}
