//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_clothe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhanhSanpham
    {
        public int ID_Image { get; set; }
        public string TenAnh { get; set; }
        public Nullable<int> Masanpham { get; set; }
    
        public virtual Sanpham Sanpham { get; set; }
    }
}
