//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_clothe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phieunhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phieunhap()
        {
            this.Chitietphieunhaps = new HashSet<Chitietphieunhap>();
        }
    
        public int ID_Phieunhap { get; set; }
        public Nullable<int> ID_Nhacungcap { get; set; }
        public System.DateTime Ngaytao { get; set; }
        public string NguoiLapPhieu { get; set; }
        public double Tongtien { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chitietphieunhap> Chitietphieunhaps { get; set; }
        public virtual Nhacungcap Nhacungcap { get; set; }
    }
}
