//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website_clothe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham()
        {
            this.Bienthesanphams = new HashSet<Bienthesanpham>();
            this.HinhanhSanphams = new HashSet<HinhanhSanpham>();
        }
    
        public int Masanpham { get; set; }
        public string Tensanpham { get; set; }
        public Nullable<int> Chitietdanhmuc { get; set; }
        public string Mota { get; set; }
        public Nullable<double> Giaban { get; set; }
        public Nullable<double> Gianhap { get; set; }
        public Nullable<int> Mathuonghieu { get; set; }
        public Nullable<int> ID_Loai { get; set; }
        public Nullable<int> ID_Nhacungcap { get; set; }
        public Nullable<System.DateTime> Ngaytao { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bienthesanpham> Bienthesanphams { get; set; }
        public virtual Chitietdanhmuc Chitietdanhmuc1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhanhSanpham> HinhanhSanphams { get; set; }
        public virtual Loai Loai { get; set; }
        public virtual Nhacungcap Nhacungcap { get; set; }
        public virtual Thuonghieu Thuonghieu { get; set; }
    }
}
